import React from "react";
import { BrandLink, FactNumber } from "../components";

const About = () => {
  return (
    <>
      <div className="flex justify-center">
        <div className="relative mx-auto my-16 md:my-20">
          <div className="absolute left-[-10px] top-0 z-[-1] h-10 w-10 rounded-full bg-yellow md:h-16 md:w-16" />
          <BrandLink classes="text-4xl sm:text-5xl md:text-6xl md:ml-6 ml-2" />
        </div>
      </div>
      <div className="py-4 sm:py-10">
        <div className="mx-auto w-4/5 text-justify md:w-2/3">
          <p className="mb-4 ">
            We are the leading omnichannel provider for premium beauty in
            Europe. Since our foundation more than 200 years ago, beauty has
            been deeply rooted in our tradition and corporate DNA. Our mission:
            We inspire our customers to live their own kind of beauty – through
            our unique range online and in around 1,850 branches. As an
            international beauty group with four corporate brands, diversity is
            not just a word for us, but a statement that we live in all of our
            activities every day.
          </p>
          <p className="">
            We are the partner of choice for brands – with selected exclusive
            brands and our strong own brands. Our range includes fragrances,
            make-up, skin care, hair care, accessories and beauty services. Our
            claim is nothing less than the best selection of brands and the best
            customer experience.
          </p>
        </div>
      </div>
      <div className="bg-yellow ">
        <div className="mx-auto flex w-3/4 flex-col items-center space-y-10 py-10 md:flex-row md:space-y-0">
          <FactNumber
            icon="people"
            number="20,000"
            title="Beauty Experts"
            description="strive to make their customers more beautiful and thus happier"
          />
          <FactNumber
            icon="coins"
            number={3.2}
            title="Billion Dollars"
            description="revenue was generated by Aphrodite in the 2016/17 financial year"
          />
          <FactNumber
            icon="shop"
            number={2000}
            title="Beauty and lifestyle products"
            description="in online shops, the beauty marketplace and in 2,000 stores"
          />
        </div>
      </div>
      <div className="mx-auto my-20 w-2/3 text-center">
        <h4 className="mb-4 font-krona">Imprint</h4>
        <p>Aphrodite Inc. Aphrodite-Heaven 7-11 40235 Aphroditee</p>
        <p>
          You can reach us by email at: service@aphrodite.heaven. Our deliveries
          go out every Sunday evening so you can get them as early in the week
          as possible
        </p>
      </div>
    </>
  );
};

export default About;
